### ISSUE TITLE
Error at start of tutorial on Win8 with Py3.4.3 

### ISSUE THREAD

**Issue by parubini** [kdavies4/natu#20]
Error output

C:\Users\Philip>py
Python 3.4.3 (v3.4.3:9b73f1c3e601, Feb 24 2015, 22:43:06) [MSC v.1600 32 bit (In
tel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from natu.units import m
>>> m
ScalarUnit m with dimension L (prefixable)
>>> length=10*m
>>> length
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python34\lib\site-packages\natu-0.1.1-py3.4.egg\natu\core.py", line 8
23, in __repr__
    return format(self, 'g')
  File "C:\Python34\lib\site-packages\natu-0.1.1-py3.4.egg\natu\core.py", line 3
57, in wrapped
    unit = unitspace(**display_unit)
  File "C:\Python34\lib\site-packages\natu-0.1.1-py3.4.egg\natu\core.py", line 1
374, in __call__
    return reduce(lambda x, y: x * y, factors)
NameError: name 'reduce' is not defined
>>>

**Comment by parubini** [comment]
It would appear that including 'from functools import reduce' in 'core.py' solves this problem
Python 3.4.3

Phil
